apiVersion: v1
kind: Service
metadata:
  name: reactapp-service2
spec:
  selector:
    app: reactapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31111